apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-hpa
  name: web-hpa
  namespace: learning
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-hpa
  template:
    metadata:
      labels:
        app: web-hpa
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 50m
